### ISSUE TITLE
Expected list, got <class 'dict'>

### ISSUE THREAD

**Issue by ashijit** [sparkmeter/sentry2csv#12]
Hello, I am getting this error on the first run of the tool installed using `pipx` -

sentry2csv version: `1.1.1`
python version: `3.8.3`
OS: `MacOS 10.15.5`

```
▶ sentry2csv --token <token-here> acmecorp 1111111 -vv
Fetching issues page 1
DEBUG:sentry2csv.sentry2csv:Fetching https://sentry.io/api/0/projects/acmecorp/1111111/issues/ with params: {'cursor': '', 'statsPeriod': '', 'query': 'is:unresolved'}
DEBUG:sentry2csv.sentry2csv:Received response: <ClientResponse(https://sentry.io/api/0/projects/acmecorp/1111111/issues/?cursor=&statsPeriod=&query=is:unresolved) [404 Not Found]>
<CIMultiDictProxy('Server': 'nginx', 'Date': 'Mon, 08 Jun 2020 12:02:44 GMT', 'Content-Type': 'application/json', 'Content-Length': '50', 'Connection': 'keep-alive', 'Access-Control-Allow-Headers': 'X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding', 'X-Content-Type-Options': 'nosniff', 'Content-Language': 'en', 'Access-Control-Expose-Headers': 'X-Sentry-Error, Retry-After', 'Vary': 'Accept-Language, Cookie', 'X-XSS-Protection': '1; mode=block', 'Allow': 'GET, PUT, DELETE, HEAD, OPTIONS', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, PUT, DELETE, HEAD, OPTIONS', 'X-Frame-Options': 'deny', 'X-Served-By': 'web-b378b859', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload')>

DEBUG:sentry2csv.sentry2csv:Received page {'detail': 'The requested resource does not exist'}
Traceback (most recent call last):
  File "/Users/ashijit/.local/bin/sentry2csv", line 8, in <module>
    sys.exit(main())
  File "/Users/ashijit/.local/pipx/venvs/sentry2csv/lib/python3.8/site-packages/sentry2csv/sentry2csv.py", line 162, in main
    loop.run_until_complete(export(args.token[0], args.organization[0], args.project[0], enrich=enrichments))
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ashijit/.local/pipx/venvs/sentry2csv/lib/python3.8/site-packages/sentry2csv/sentry2csv.py", line 119, in export
    issues = await fetch_issues(session, issues_url)
  File "/Users/ashijit/.local/pipx/venvs/sentry2csv/lib/python3.8/site-packages/sentry2csv/sentry2csv.py", line 78, in fetch_issues
    assert isinstance(resp, list), f"Bad response type. Expected list, got {type(resp)}"
AssertionError: Bad response type. Expected list, got <class 'dict'>
```

**Comment by ashijit** [comment]
This was not a bug, I was mistakenly using the numerical project ID instead of the project name.

**Comment by arusahni** [comment]
Thanks for following up! I'll see if there's a way I can update this to emit a more helpful error message in the event the the project doesn't exist.
