### ISSUE TITLE
Doesn't seem to work on latest sentry

### ISSUE THREAD

**Issue by alexbhandari** [sparkmeter/sentry2csv#17]
I get the following error 

```
Fetching issues page 1
Traceback (most recent call last):
  File "/Users/<username>/miniconda3/bin/sentry2csv", line 10, in <module>
    sys.exit(main())
  File "/Users/<username>/miniconda3/lib/python3.7/site-packages/sentry2csv/sentry2csv.py", line 191, in main
    export(args.token[0], args.organization[0], args.project[0], enrich=enrichments, host=args.host[0])
  File "/Users/<username>/miniconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/<username>/miniconda3/lib/python3.7/site-packages/sentry2csv/sentry2csv.py", line 139, in export
    issues = await fetch_issues(session, issues_url)
  File "/Users/<username>/miniconda3/lib/python3.7/site-packages/sentry2csv/sentry2csv.py", line 80, in fetch_issues
    assert isinstance(resp, list), f"Bad response type. Expected list, got {type(resp)}"
AssertionError: Bad response type. Expected list, got <class 'dict'>
```

**Comment by alexbhandari** [comment]
This issue seems similar or same: https://github.com/sparkmeter/sentry2csv/issues/12
But I am using params: org_name project_name token as stated in the docs

**Comment by alexbhandari** [comment]
Ah I had params in the wrong order :)
It works fine

**Comment by arusahni** [comment]
@alexbhandari glad you got it sorted out! I'll investigate ways to improve the legibility of this sort of error message.
